#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DevoirSNCF_Ivan_Naluzhnyi.Resource", IsApplication=true)]

namespace DevoirSNCF_Ivan_Naluzhnyi
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int btnIncrirAg = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int btnListInsc = 2130968577;
			
			// aapt resource value: 0x7f04000e
			public const int btnValider = 2130968590;
			
			// aapt resource value: 0x7f04000b
			public const int lstActivite = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int lstFormation = 2130968589;
			
			// aapt resource value: 0x7f040002
			public const int lstInscrit = 2130968578;
			
			// aapt resource value: 0x7f04000f
			public const int lstNewInsc = 2130968591;
			
			// aapt resource value: 0x7f040009
			public const int switch1 = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int textCode = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int textForma = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int textLibelle = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int textNewCode = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int textNewNom = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int textNom = 2130968581;
			
			// aapt resource value: 0x7f04000a
			public const int textView1 = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int textView2 = 2130968588;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int InscritLayout = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ItemActivite = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ItemFormation = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ItemInscrit = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ItemNewInscription = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Main = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int NewInscriptionLayout = 2130837510;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ip = 2130903041;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
